<html><head><style><!-- a:link{color: #ee8800;} a:visited{color: #ee4400;} pre{font-size:80%; padding:0.5em; background-color: #eee; border: 1px dashed;}--></style></head><body><p>all: *
	for FILE in *;do perl make-html.pl <$$FILE >html/$$FILE; done
</p></body></html>
